* Dependency Installation
The aquarium uses Raylib. Compile and install it (as a static library).

#+BEGIN_SRC bash
  sudo apt install build-essential git libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libgflw3-dev # Debian based systems
  git clone https://github.com/raysan5/raylib.git raylib
  cd raylib/src
  make PLATFORM=PLATFORM_DESKTOP GRAPHICS=GRAPHICS_API_OPENGL_33 -j$(nproc)
  sudo make install
#+END_SRC

* TODO Compilation of Aquarium
#+BEGIN_SRC bash
  # from the root of the project
  pwd # should be something like /path/to/fishy-merry-go-round/
  make -j$(nproc)
#+END_SRC

* TODO Running
** With Scanner
With a scanner, print out a few copies of the templates found under resources/templates/. 

Run the aquarium software suite with: 
#+BEGIN_SRC bash
  # from the root of the project
  MESH_GL_VERSION_OVERRIDE=3.3 ./main.out
  python scanner.py --cam 2 --path resoures/textures/ # running the scanner application
#+END_SRC

For calibration, run scanner.py and adjust lights in the scanner box until the entire fish is visible in the preview window. Use the "s" key to take and save the image. The scanned fish will be visible in the screen, given sufficient space and time for it to load. It's usually instantaneous. To exit the scanning, hit "q".

A maximum of about 200 fish are visible well, on a 16:10 screen. Too many, and it can become quite the school!

** With Pre-Made Artwork
Check releases for the files, unzip it under resources/textures, and watch as the fish start spawning, one-by-one!

Here are the steps for that:
#+BEGIN_SRC bash
  # from root of the project
  unzip /path/to/MakerFaire23-<choose which one>.zip -d resources/textures/

  # now, start with:
  MESH_GL_VERSION_OVERRIDE=3.3  ./main.out
#+END_SRC

* Artwork
All of the art is licensed under CC BY-SA 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-sa/4.0/. 

The fish templates were created by [[https://www.instagram.com/kottimira_worma/][@kottimira_worma]].

 All the files in the zip's were templates coloured in by the visitors of MakerFaire Hyderabad 2023. One love <3 to everyone who contributed a fish (or two).
